# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-13 05:02
from __future__ import unicode_literals

import association.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100, verbose_name='活动名称')),
                ('activity_content', models.TextField(null=True, verbose_name='活动内容')),
                ('activity_site', models.CharField(max_length=200, verbose_name='活动地点')),
                ('activity_start', models.DateTimeField(verbose_name='开始时间')),
                ('activity_end', models.DateTimeField(verbose_name='结束时间')),
                ('activity_praise', models.IntegerField(default=0, verbose_name='活动点赞')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_num', models.CharField(max_length=20, unique=True, verbose_name='社团编号')),
                ('association_pwd', models.CharField(max_length=500, verbose_name='社团密码')),
                ('association_name', models.CharField(max_length=100, verbose_name='协会名称')),
                ('association_info', models.TextField(null=True, verbose_name='协会信息')),
                ('association_mail', models.CharField(max_length=100, null=True, verbose_name='社团邮箱')),
                ('association_tel', models.CharField(max_length=100, null=True, verbose_name='社团手机')),
                ('association_start', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('association_join', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('association_praise', models.IntegerField(default=0, verbose_name='社团点赞')),
                ('association_type', models.IntegerField(choices=[(1, '艺术'), (2, '文学'), (3, '运动'), (3, '学术')], verbose_name='社团类别')),
                ('association_growth', models.IntegerField(default=0, verbose_name='成长值')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('apply_status', models.IntegerField(choices=[(1, '待审核'), (2, '通过'), (3, '驳回'), (4, '待完善')], default=1, verbose_name='审核状态')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Academy')),
                ('students', models.ManyToManyField(to='student.Student', verbose_name='协会成员')),
            ],
            options={
                'db_table': 'association',
            },
        ),
        migrations.CreateModel(
            name='AssociationStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateField(auto_now_add=True, verbose_name='加入时间')),
                ('student_position', models.IntegerField(choices=[(1, '成员'), (2, '干事'), (3, '副部长'), (4, '部长'), (5, '副社长'), (6, '社长')], default=1, verbose_name='职务')),
                ('is_paid', models.IntegerField(choices=[(1, '未缴费'), (2, '已缴费'), (3, '')], default=1, verbose_name='是否缴纳会费')),
                ('apply_to_stu', models.IntegerField(choices=[(1, '待回复'), (2, '已同意'), (3, '已拒绝')], default=1, verbose_name='邀请请求状态')),
                ('apply_to_ass', models.IntegerField(choices=[(1, '待回复'), (2, '已同意'), (3, '已拒绝')], default=1, verbose_name='入团请求状态')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.Association')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'db_table': 'association_student',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_name', models.CharField(max_length=100, verbose_name='相册名称')),
                ('permission', models.IntegerField(choices=[(1, '公开'), (2, '私密')], verbose_name='权限')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.Association', verbose_name='社团')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='学生')),
            ],
        ),
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.IntegerField(choices=[(1, '社团头像'), (2, '用户头像'), (3, '相册文件'), (4, '图片文件'), (5, '普通文件')], default=5, verbose_name='文件说明')),
                ('relative_path', models.CharField(default='', max_length=500, verbose_name='相对路径')),
                ('filename', models.CharField(max_length=100, null=True, verbose_name='文件名字')),
                ('file', models.FileField(null=True, upload_to=association.models.upload_to, verbose_name='文件')),
                ('imagefile', models.ImageField(null=True, upload_to=association.models.upload_to, verbose_name='图片文件')),
                ('file_date', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='association.Association', verbose_name='社团')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='association.Gallery', verbose_name='相册')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='学生')),
            ],
            options={
                'db_table': 'userfiles',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.Association'),
        ),
        migrations.AddField(
            model_name='activity',
            name='students',
            field=models.ManyToManyField(to='student.Student', verbose_name='参与人员'),
        ),
    ]
