# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-13 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_end',
            field=models.DateField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_start',
            field=models.DateField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='association',
            name='association_join',
            field=models.DateField(auto_now_add=True, verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='association',
            name='association_start',
            field=models.DateField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userfiles',
            name='file_date',
            field=models.DateField(auto_now_add=True, verbose_name='上传时间'),
        ),
    ]
