# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-13 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_auto_20190413_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_end',
            field=models.DateTimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_start',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='permission',
            field=models.IntegerField(choices=[(2, '私密'), (1, '公开')], verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='userfiles',
            name='file_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
    ]
