# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-14 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190413_1406'),
        ('association', '0004_auto_20190413_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('part', models.IntegerField(choices=[(1, '参与者'), (1, '主要参与者'), (1, '组织者')], default=1, verbose_name='角色')),
                ('join_status', models.IntegerField(choices=[(1, '已报名'), (2, '通过报名'), (3, '报名被拒绝')], default=1, verbose_name='报名状态')),
                ('awards', models.IntegerField(choices=[(0, '未获奖'), (1, '一级奖项'), (2, '二级奖项'), (3, '三级奖项'), (4, '四级奖项')], default=0, verbose_name='获奖情况')),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='成员备注')),
            ],
            options={
                'db_table': 'activity_student',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_conndition',
            field=models.IntegerField(choices=[(1, '直接加入'), (2, '缴费参与')], default=1, verbose_name='参与条件'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_detail',
            field=models.TextField(null=True, verbose_name='活动详情'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_labelk',
            field=models.IntegerField(default=0, verbose_name='活动标签'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_remark',
            field=models.IntegerField(default=0, verbose_name='活动备注'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_status',
            field=models.IntegerField(choices=[(1, '未提交'), (2, '待审批'), (3, '待补充'), (4, '已通过审批'), (5, '未通过审批'), (6, '进行中'), (7, '已结束')], default=1, verbose_name='活动状态'),
        ),
        migrations.AddField(
            model_name='userfiles',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='association.Activity', verbose_name='活动'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_end',
            field=models.DateTimeField(null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_start',
            field=models.DateTimeField(null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='userfiles',
            name='file_type',
            field=models.IntegerField(choices=[(1, '社团头像'), (2, '用户头像'), (3, '相册文件'), (4, '图片文件'), (5, '普通文件'), (6, '社团审批文件'), (7, '活动审批文件')], default=5, verbose_name='文件说明'),
        ),
        migrations.AddField(
            model_name='activitystudent',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.Activity'),
        ),
        migrations.AddField(
            model_name='activitystudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
