# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0006_auto_20190415_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_remark',
            field=models.TextField(default='', verbose_name='活动备注'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='permission',
            field=models.IntegerField(choices=[(2, '私密'), (1, '公开')], verbose_name='权限'),
        ),
    ]
