# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-15 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0007_auto_20190415_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_label',
            field=models.IntegerField(default=0, null=True, verbose_name='活动标签'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_remark',
            field=models.TextField(null=True, verbose_name='活动备注'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_site',
            field=models.CharField(max_length=200, null=True, verbose_name='活动地点'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='permission',
            field=models.IntegerField(choices=[(1, '公开'), (2, '私密')], verbose_name='权限'),
        ),
    ]
