# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-15 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0008_auto_20190415_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='permission',
            field=models.IntegerField(choices=[(2, '私密'), (1, '公开')], verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='userfiles',
            name='filename',
            field=models.CharField(max_length=500, null=True, verbose_name='文件名字'),
        ),
    ]
