# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-15 14:19
from __future__ import unicode_literals

import association.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0010_auto_20190415_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiles',
            name='file',
            field=models.FileField(max_length=1000, null=True, upload_to=association.models.upload_to, verbose_name='文件'),
        ),
    ]
