# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0012_auto_20190418_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='create_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='describe',
            field=models.TextField(null=True, verbose_name='相册描述'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='permission',
            field=models.IntegerField(choices=[(1, '所有人可见'), (3, '仅自己可见'), (2, '社团内部可见')], verbose_name='权限'),
        ),
    ]
