# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0013_auto_20190418_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='association.Association', verbose_name='社团'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='学生'),
        ),
    ]
