# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0014_auto_20190418_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='association.Activity', verbose_name='活动'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='permission',
            field=models.IntegerField(choices=[(1, '所有人可见'), (2, '社团内部可见'), (3, '仅自己可见')], verbose_name='权限'),
        ),
    ]
