# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0015_auto_20190418_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiles',
            name='file_type',
            field=models.IntegerField(choices=[(1, '头像'), (2, '审批文件'), (3, '相册'), (4, '图片'), (5, '普通')], default=5, verbose_name='文件说明'),
        ),
        migrations.AlterModelTable(
            name='gallery',
            table='gallery',
        ),
    ]
