# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 16:33
from __future__ import unicode_literals

import association.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0016_auto_20190418_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='permission',
            field=models.IntegerField(choices=[(3, '仅自己可见'), (2, '社团内部可见'), (1, '所有人可见')], verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='userfiles',
            name='imagefile',
            field=models.ImageField(max_length=1000, null=True, upload_to=association.models.upload_to, verbose_name='图片文件'),
        ),
    ]
