# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-13 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=20, null=True, verbose_name='姓名')),
                ('stu_num', models.CharField(max_length=20, null=True, verbose_name='学号')),
                ('stu_pwd', models.CharField(max_length=200, verbose_name='学生密码')),
                ('stu_birth', models.CharField(max_length=20, null=True, verbose_name='出生年月')),
                ('stu_sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别')),
                ('stu_tel', models.CharField(max_length=11, verbose_name='手机')),
                ('stu_mail', models.EmailField(max_length=100, null=True, verbose_name='邮箱')),
                ('stu_motto', models.CharField(max_length=200, null=True, verbose_name='签名')),
                ('stu_head', models.ImageField(null=True, upload_to='student/images/', verbose_name='头像')),
                ('stu_growth', models.IntegerField(default=0, verbose_name='成长值')),
                ('join_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('academy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.Academy', verbose_name='学校')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.Major', verbose_name='系别')),
                ('stu_native', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.Area', verbose_name='籍贯')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
