# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-13 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190413_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_birth',
            field=models.DateField(max_length=20, null=True, verbose_name='出生年月'),
        ),
    ]
